/**
 * Embeds the Help24 app icon into a TypeScript constant for the OpenGraph card.
 *
 * WHY THE ICON HAS TO BE INLINED
 * ------------------------------
 * `app/download/opengraph-image.tsx` runs on the EDGE runtime — deliberately,
 * because the Node bundle of `@vercel/og` breaks `next build` on Windows (see
 * that file's comments). The edge runtime has no filesystem, so it cannot read
 * `public/help24-icon.png`, and fetching it over HTTP at build time would make
 * the build depend on the deployment it is producing. A data URI compiled into
 * the bundle is the only option that is both correct and portable.
 *
 * WHY IT IS DOWNSCALED FIRST
 * --------------------------
 * The source icon is 1024×1024 / 177 KB, which is 236 KB once base64-encoded —
 * absurd for a mark that renders at 112 CSS pixels. This resamples to 224 px
 * (2× for retina) and strips metadata, which lands around 6 KB of base64.
 *
 *   npm run generate:og-icon
 *
 * Re-run only when the app icon itself changes.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const here = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(here, "..", "public", "help24-icon.png");
const OUT = resolve(here, "..", "lib", "generated", "app-icon.ts");

/** Rendered at 112px in the card; 2× keeps it sharp on retina unfurls. */
const RENDER_SIZE = 224;

const source = readFileSync(SRC);
const resized = await sharp(source)
  .resize(RENDER_SIZE, RENDER_SIZE, { fit: "cover" })
  // Palette quantisation: the icon is flat brand artwork with few colours, so
  // this is lossless to the eye and roughly halves the payload.
  .png({ compressionLevel: 9, palette: true })
  .toBuffer();

const dataUri = `data:image/png;base64,${resized.toString("base64")}`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `// GENERATED by scripts/generate-og-icon.mjs — do not edit by hand.
// Source: public/help24-icon.png, resampled to ${RENDER_SIZE}×${RENDER_SIZE}.
// Regenerate with: npm run generate:og-icon

/** The Help24 app icon as a data URI, for the edge-rendered OpenGraph card. */
export const APP_ICON_DATA_URI =
  "${dataUri}";
`,
  "utf8",
);

const kb = (n) => `${(n / 1024).toFixed(1)} KB`;
console.log(
  `wrote ${OUT}\n  ${RENDER_SIZE}×${RENDER_SIZE} · ${kb(source.length)} source → ${kb(resized.length)} png → ${kb(dataUri.length)} base64`,
);
