/**
 * Regenerates lib/generated/places.ts from the Flutter app's location registry.
 *
 * WHY A GENERATED COPY AND NOT AN IMPORT. help24_website is its own repository
 * (alphwan14/help24_website) and Vercel builds it standing alone — there is no
 * mobile-app/ next to it on the build machine. Reaching across the two working
 * copies would build here and fail there, which is the worst kind of break.
 *
 * WHY THE APP'S FILE IS THE SOURCE. The ids in locations_ke.json are the ones
 * the server's `locations` table uses (migration 088 seeds them byte-identical).
 * A slug invented for the website would be a second vocabulary for the same
 * places, and the first time somebody tried to join a web URL to a post's
 * location it would not line up. The URL /areas/mombasa therefore carries the
 * same string the database does.
 *
 * WHAT IS DROPPED. Aliases and search weights are app concerns. The website
 * needs name, kind, parent, county, and coordinates — nothing else travels.
 *
 *   node scripts/sync-places.mjs [path-to-locations_ke.json]
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = resolve(
  here,
  process.argv[2] ?? "../../mobile-app/assets/data/locations_ke.json",
);
const target = resolve(here, "../lib/generated/places.ts");

const raw = JSON.parse(readFileSync(source, "utf8"));
if (raw.schema !== 1) throw new Error(`Unexpected schema ${raw.schema}`);

const places = raw.places;
const cities = places.filter((p) => p.t === "city");
const towns = places.filter((p) => p.t === "town");
const areasFor = (id) => places.filter((p) => p.p === id);

// Neighbourhoods are emitted only for the places that have them. A city with an
// empty list is still a city; it just has nothing below it to name.
const line = (p) => {
  const bits = [
    `id: ${JSON.stringify(p.i)}`,
    `name: ${JSON.stringify(p.n)}`,
    `county: ${JSON.stringify(p.c)}`,
  ];
  if (p.lat !== undefined) bits.push(`lat: ${p.lat}`, `lng: ${p.lng}`);
  const kids = areasFor(p.i);
  if (kids.length) {
    bits.push(
      `neighbourhoods: [${kids.map((k) => JSON.stringify(k.n)).join(", ")}]`,
    );
  }
  return `  { ${bits.join(", ")} },`;
};

const out = `// GENERATED by scripts/sync-places.mjs — do not edit by hand.
// Source: mobile-app/assets/data/locations_ke.json (registry version ${raw.version}),
// which is itself byte-identical to the server's \`locations\` seed.
// Regenerate with: npm run sync:places

export interface Place {
  /** The registry slug. Also the URL segment. NEVER rename one of these. */
  id: string;
  name: string;
  county: string;
  lat?: number;
  lng?: number;
  /** Real sub-places from the registry. Absent where the registry has none. */
  neighbourhoods?: string[];
}

/** The ${cities.length} places the registry classes as cities, registry order. */
export const CITIES: Place[] = [
${cities.map(line).join("\n")}
];

/** County headquarters and larger towns — named in copy, not given own pages. */
export const TOWNS: Place[] = [
${towns
  .filter((t) => t.hq)
  .map(line)
  .join("\n")}
];
`;

writeFileSync(target, out, "utf8");
console.log(
  `places.ts: ${cities.length} cities, ${towns.filter((t) => t.hq).length} HQ towns, ` +
    `${cities.filter((c) => areasFor(c.i).length).length} cities with neighbourhoods`,
);
